#!/usr/bin/env node
/**
 * Builds derived data artifacts from the budget files in data/budgets/:
 *
 *  1. data/budgets/index.json - a manifest listing all available budgets,
 *     used by index.html to populate the budget selector automatically.
 *  2. data/budgets-embedded.js - all budget data bundled as a script,
 *     used as a fallback so the visualization also works when index.html
 *     is opened directly from disk (file://), where fetch() is blocked.
 *
 * Run this after adding or editing budget files:
 *   npm run build-data
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const BUDGETS_DIR = path.join(ROOT, 'data', 'budgets');
const MANIFEST_PATH = path.join(BUDGETS_DIR, 'index.json');
const EMBEDDED_PATH = path.join(ROOT, 'data', 'budgets-embedded.js');

function main() {
  const files = fs
    .readdirSync(BUDGETS_DIR)
    .filter((f) => f.endsWith('.json') && f !== 'index.json')
    .sort();

  if (files.length === 0) {
    console.error('No budget files found in data/budgets/.');
    process.exit(1);
  }

  const budgets = {};
  const manifestEntries = [];

  for (const file of files) {
    const filepath = path.join(BUDGETS_DIR, file);
    let data;
    try {
      data = JSON.parse(fs.readFileSync(filepath, 'utf8'));
    } catch (e) {
      console.error(`Skipping ${file}: invalid JSON (${e.message})`);
      process.exitCode = 1;
      continue;
    }

    const meta = data.metadata || {};
    const relPath = `data/budgets/${file}`;
    const label = meta.country && meta.year ? `${meta.country} ${meta.year}` : file.replace(/\.json$/, '');

    manifestEntries.push({
      value: relPath,
      label,
      country: meta.country || null,
      year: meta.year || null,
      currency: meta.currency || null,
    });
    budgets[relPath] = data;
  }

  // Sort by country name, then year descending
  manifestEntries.sort((a, b) => {
    const byCountry = String(a.country).localeCompare(String(b.country));
    return byCountry !== 0 ? byCountry : (b.year || 0) - (a.year || 0);
  });

  const manifest = {
    generated: new Date().toISOString().slice(0, 10),
    budgets: manifestEntries,
  };

  fs.writeFileSync(MANIFEST_PATH, JSON.stringify(manifest, null, 2) + '\n');
  console.log(`Wrote ${path.relative(ROOT, MANIFEST_PATH)} (${manifestEntries.length} budgets)`);

  const embedded =
    '// AUTO-GENERATED by scripts/build-data.js - do not edit by hand.\n' +
    '// Bundles the budget manifest and data so index.html also works when\n' +
    '// opened directly from disk (file://), where fetch() is unavailable.\n' +
    'window.EMBEDDED_BUDGETS = ' +
    JSON.stringify({ manifest, budgets }, null, 2) +
    ';\n';

  fs.writeFileSync(EMBEDDED_PATH, embedded);
  console.log(`Wrote ${path.relative(ROOT, EMBEDDED_PATH)}`);
}

main();
