#!/usr/bin/env node
/**
 * Cross-checks the general-government budget files against curated
 * reference series from Our World in Data (data/reference/owid.json,
 * generated by scripts/fetch-owid-reference.js).
 *
 * For every general-scope country-year it compares:
 *   - each mapped expenditure category as % of GDP
 *   - total expenditure as % of GDP
 * against the OWID value for that country and year, and flags deviations.
 *
 * Definitions differ slightly between sources (e.g. SIPRI military vs
 * COFOG defence), so deviations are informational: within the tolerance
 * prints OK, outside prints DEV with both values. Exit code is always 0
 * unless the reference exists and a deviation exceeds the hard limit.
 */

const fs = require('fs');
const path = require('path');

const BUDGETS_DIR = path.join(__dirname, '..', 'data', 'budgets');
const REF_PATH = path.join(__dirname, '..', 'data', 'reference', 'owid.json');

const SOFT_TOLERANCE = 0.15; // 15% relative deviation -> DEV warning
const HARD_LIMIT = 0.40;     // 40% relative deviation -> error (exit 1)
const MIN_PP = 0.3;          // ignore deviations below 0.3 percentage points

const COUNTRY_CODES = {
  'Germany': 'DEU',
  'France': 'FRA',
  'Denmark': 'DNK',
  'United Kingdom': 'GBR',
  'United States': 'USA',
  'China': 'CHN',
  'Italy': 'ITA',
  'Spain': 'ESP',
  'Sweden': 'SWE',
  'Japan': 'JPN',
};

function baseCountry(name) {
  return String(name).replace(/\s*\(general government\)$/i, '');
}

function main() {
  if (!fs.existsSync(REF_PATH)) {
    console.log('No OWID reference found (data/reference/owid.json).');
    console.log('Run "node scripts/fetch-owid-reference.js" on a machine with internet access first.');
    process.exit(0);
  }
  const ref = JSON.parse(fs.readFileSync(REF_PATH, 'utf8'));
  if (ref.provisional_seed) {
    console.log('NOTE: reference file is a provisional seed, not fetched from OWID.');
    console.log('Regenerate with "node scripts/fetch-owid-reference.js" for authoritative values.\n');
  }

  const files = fs.readdirSync(BUDGETS_DIR)
    .filter(f => f.endsWith('.json') && f !== 'index.json');

  let checked = 0, deviations = 0, hardFailures = 0;

  for (const file of files) {
    const doc = JSON.parse(fs.readFileSync(path.join(BUDGETS_DIR, file), 'utf8'));
    const meta = doc.metadata || {};
    if (meta.scope !== 'general' || !(meta.gdp > 0)) continue;
    const code = COUNTRY_CODES[baseCountry(meta.country)];
    if (!code) continue;

    const catSums = {};
    (doc.expenditure || []).forEach(i => {
      catSums[i.category] = (catSums[i.category] || 0) + i.amount;
    });

    for (const [slug, series] of Object.entries(ref.series || {})) {
      const refVal = series.values && series.values[code] && series.values[code][meta.year];
      if (typeof refVal !== 'number') continue;

      const ours = series.measure === 'total'
        ? (meta.total_expenditure / meta.gdp) * 100
        : ((catSums[series.category] || 0) / meta.gdp) * 100;

      checked++;
      const relDiff = Math.abs(ours - refVal) / refVal;
      const ppDiff = Math.abs(ours - refVal);
      const label = `${baseCountry(meta.country)} ${meta.year} ${series.measure === 'total' ? 'Total expenditure' : series.category}`;
      if (ppDiff < MIN_PP || relDiff <= SOFT_TOLERANCE) {
        console.log(`[OK]  ${label}: ours ${ours.toFixed(2)}% vs OWID ${refVal.toFixed(2)}% of GDP`);
      } else if (relDiff <= HARD_LIMIT) {
        deviations++;
        console.log(`[DEV] ${label}: ours ${ours.toFixed(2)}% vs OWID ${refVal.toFixed(2)}% of GDP (${(relDiff * 100).toFixed(0)}% off)${series.note ? ' - ' + series.note : ''}`);
      } else {
        hardFailures++;
        console.log(`[ERR] ${label}: ours ${ours.toFixed(2)}% vs OWID ${refVal.toFixed(2)}% of GDP (${(relDiff * 100).toFixed(0)}% off)`);
      }
    }
  }

  console.log(`\n${checked} value(s) checked, ${deviations} deviation(s), ${hardFailures} hard failure(s).`);
  process.exit(hardFailures > 0 ? 1 : 0);
}

main();
